### ISSUE TITLE
There was a problem installing InstaPy

### ISSUE THREAD

**Issue by joost-heijden** [InstaPy/instapy-quickstart#12]
InstaPy doesn't work, it gives me the following error:

```
Traceback (most recent call last):
  File "../quickstart.py", line 15, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces voltooid]
```

Did the install by: **sudo pip3 install instapy --ignore-installed**. But it gives me this error.

Who can help me out?

**Comment by joost-heijden** [comment]
@timgrossmann

**Comment by timgrossmann** [comment]
@joost-heijden You know, tagging me doesn't make me respond faster 😉 It does not change anything in the way the issue is displayed in the GitHub Notifications.

Without more context, I don't know where the problem is, I'm sorry.
Please use the discord channel linked in the main repository to get help from many people!
Thank you very much 😊

**Comment by fudojahic** [comment]
did anyone fix this?
